package org.threehundredtutor.junit.mockk_date

//fun getAllCountryList() = listOf(
//    "Argentina",
//    "Australia",
//    "Austria",
//    "Belgium",
//    "Brazil",
//    "Bulgaria",
//    "Canada",
//    "China",
//    "Colombia",
//    "Cuba",
//    "Czech Republic",
//    "Egypt",
//    "France",
//    "Germany",
//    "Greece",
//    "Hong Kong",
//    "Hungary",
//    "India",
//    "Indonesia",
//    "Ireland",
//    "Israel",
//    "Italy",
//    "Japan",
//    "Latvia",
//    "Lithuania",
//    "Malaysia",
//    "Mexico",
//    "Morocco",
//    "Netherlands",
//    "New Zealand",
//    "Nigeria",
//    "Norway",
//    "Philippines",
//    "Poland",
//    "Portugal",
//    "Romania",
//    "Russia",
//    "Saudi Arabia",
//    "Serbia",
//    "Singapore",
//    "Slovakia",
//    "Slovenia",
//    "South Africa",
//    "South Korea",
//    "Sweden",
//    "Switzerland",
//    "Taiwan",
//    "Thailand",
//    "Turkey",
//    "Ukraine",
//    "UAE",
//    "United Kingdom",
//    "United States",
//    "Venezuela"
//)
//
//fun getAllowedCountryList() = listOf(
//    "Argentina",
//    "Australia",
//    "Austria",
//    "Belgium",
//    "Brazil",
//    "Bulgaria",
//    "Canada",
//    "China",
//    "Colombia",
//    "Cuba",
//    "Czech Republic",
//    "Egypt",
//    "France",
//    "Germany",
//    "Greece",
//    "Hong Kong",
//    "Hungary",
//    "India",
//    "Indonesia",
//    "Ireland",
//    "Israel",
//    "Italy",
//    "Japan",
//    "Latvia",
//    "Lithuania",
//    "Malaysia",
//    "Mexico",
//    "Morocco",
//    "Netherlands",
//    "New Zealand",
//    "Nigeria",
//    "Norway",
//    "Philippines",
//    "Poland",
//    "Portugal",
//    "Romania",
//    "Russia",
//    "Saudi Arabia",
//    "Serbia",
//    "Singapore",
//    "Slovakia",
//    "Slovenia",
//    "South Africa",
//    "South Korea",
//    "Sweden",
//    "Switzerland",
//    "Taiwan",
//    "Thailand",
//    "Turkey",
//    "Ukraine",
//    "UAE",
//    "United Kingdom",
//    "United States",
//    "Venezuela"
//)
//
//fun getAllIdCountry() =
//    listOf(
//        "ar",
//        "au",
//        "at",
//        "be",
//        "br",
//        "bg",
//        "ca",
//        "cn",
//        "co",
//        "cu",
//        "cz",
//        "eg",
//        "fr",
//        "de",
//        "gr",
//        "hk",
//        "hu",
//        "in",
//        "id",
//        "ie",
//        "il",
//        "it",
//        "jp",
//        "lv",
//        "lt",
//        "my",
//        "mx",
//        "ma",
//        "nl",
//        "nz",
//        "ng",
//        "no",
//        "ph",
//        "pl",
//        "pt",
//        "ro",
//        "ru",
//        "sa",
//        "rs",
//        "sg",
//        "sk",
//        "si",
//        "za",
//        "kr",
//        "se",
//        "ch",
//        "tw",
//        "th",
//        "tr",
//        "ua",
//        "ae",
//        "gb",
//        "us",
//        "ve"
//    )
//
//fun getAllowedIdCountry() =
//    listOf(
//        "ar",
//        "au",
//        "at",
//        "be",
//        "br",
//        "bg",
//        "ca",
//        "cn",
//        "co",
//        "cu",
//        "cz",
//        "eg",
//        "fr",
//        "de",
//        "gr",
//        "hk",
//        "hu",
//        "in",
//        "id",
//        "ie",
//        "il",
//        "it",
//        "jp",
//        "lv",
//        "lt",
//        "my",
//        "mx",
//        "ma",
//        "nl",
//        "nz",
//        "ng",
//        "no",
//        "ph",
//        "pl",
//        "pt",
//        "ro",
//        "ru",
//        "sa",
//        "rs",
//        "sg",
//        "sk",
//        "si",
//        "za",
//        "kr",
//        "se",
//        "ch",
//        "tw",
//        "th",
//        "tr",
//        "ua",
//        "ae",
//        "gb",
//        "us",
//        "ve"
//    )
//